# Dockerfile-gradio
FROM python:3.10

# Install the timezone data package
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
        apt-get install -y tzdata && \
        rm -rf /var/lib/apt/lists/*

# Set the timezone to Asia/Shanghai
ENV TZ=Asia/Shanghai
# Copy the local time file to the container
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime \
        && echo $TZ > /etc/timezone

# 设置工作目录为/app
WORKDIR /app

#设置工作目录
WORKDIR /workspace

COPY examples/gradio_openai_chatbot_webserver.py /app

RUN pip install --no-cache-dir gradio  openai

RUN chmod u+x /app/gradio_openai_chatbot_webserver.py

#开启7860端口
EXPOSE 7860

#设置启动命令
#ENTRYPOINT ["python", "llama_chat_gradio.py", \
#            "--model_name_or_path=/workspace/models"]
