# Dockerfile-gradio
FROM python:3.10

# Install the timezone data package
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
        apt-get install -y tzdata && \
        rm -rf /var/lib/apt/lists/*

# Set the timezone to Asia/Shanghai
ENV TZ=Asia/Shanghai
# Copy the local time file to the container
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime \
        && echo $TZ > /etc/timezone

# 设置工作目录为/app
WORKDIR /app
COPY examples/gradio_openai_chatbot_webserver.py /app
RUN chmod u+x /app/gradio_openai_chatbot_webserver.py

RUN pip install --no-cache-dir gradio  openai

#开启7860端口
EXPOSE 7860

RUN wget https://cdn-media.hf-mirror.com/frpc-gradio-0.2/frpc_linux_amd64 && \
    mv frpc_linux_amd64 frpc_linux_amd64_v0.2 && \
    mv frpc_linux_amd64_v0.2 /usr/local/lib/python3.10/site-packages/gradio/ && \
    chmod 755 /usr/local/lib/python3.10/site-packages/gradio/

#设置启动命令
#ENTRYPOINT ["python", "llama_chat_gradio.py", \
#            "--model_name_or_path=/workspace/models"]
