# Dockerfile-llama
FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-devel

# Install the timezone data package
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
        apt-get install -y tzdata && \
        rm -rf /var/lib/apt/lists/*

# Set the timezone to Asia/Shanghai
ENV TZ=Asia/Shanghai
# Copy the local time file to the container
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime \
        && echo $TZ > /etc/timezone

RUN apt-get update -y --allow-unauthenticated
RUN apt install -y git vim git-lfs pip wget

RUN pip install --no-cache-dir \
    -i https://pypi.tuna.tsinghua.edu.cn/simple \
    --trusted-host pypi.tuna.tsinghua.edu.cn \
    bitsandbytes==0.43.1 \
    accelerate==0.30.1 \
    numpy==1.26.4 \
    gekko==1.0.6 \
    pandas \
    scipy \
    sentencepiece==0.2.0 \
    datasets \
    evaluate \
    pytest \
    peft==0.10.0 \
    transformers==4.43.3 \
    deepspeed==0.14.0 \
    scikit-learn \
    torchvision \
    pytorchvideo \
    torchdata \
    torchaudio \
    tensorboard \
    gradio \
    packaging \
    tqdm \
    rouge \
    jieba \
    fuzzywuzzy \
    einops \
    tiktoken \
    xformers \
    streamlit \
    cpm_kernels \
    decord>=0.6.0 \
    chainlit \
    autoawq autoawq-kernels \
    auto_gptq optimum

RUN pip install --no-cache-dir flash_attn --no-build-isolation


RUN wget https://cdn-media.hf-mirror.com/frpc-gradio-0.2/frpc_linux_amd64 && \
    mv frpc_linux_amd64 frpc_linux_amd64_v0.2 && \
    mv frpc_linux_amd64_v0.2 /opt/conda/lib/python3.10/site-packages/gradio/ && \
    chmod 755 /opt/conda/lib/python3.10/site-packages/gradio/frpc_linux_amd64_v0.2

#设置工作目录
WORKDIR /workspace

COPY examples/llama_chat_gradio.py /workspace
COPY examples/chatglm_chat_gradio.py /workspace
COPY examples/chatglm3_chat_gradio.py /workspace

RUN chmod u+x /workspace/llama_chat_gradio.py
RUN chmod u+x /workspace/chatglm_chat_gradio.py
RUN chmod u+x /workspace/chatglm3_chat_gradio.py

#开启7860端口
EXPOSE 7860

#设置启动命令
#ENTRYPOINT ["python", "llama_chat_gradio.py", \
#            "--model_name_or_path=/workspace/models"]
