# Dockerfile-qwen2vl
FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-devel
#FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

# Install the timezone data package
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
        apt-get install -y tzdata && \
        rm -rf /var/lib/apt/lists/*

# Set the timezone to Asia/Shanghai
ENV TZ=Asia/Shanghai
# Copy the local time file to the container
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime \
        && echo $TZ > /etc/timezone

#RUN apt-get install -y git tmux htop vim pip wget \
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y git tmux htop vim git-lfs pip wget && \
    rm -rf /var/lib/apt/lists/*

RUN pip install -U flash-attn --no-build-isolation --use-pep51

RUN pip install --no-cache-dir  \
        -i https://pypi.tuna.tsinghua.edu.cn/simple  \
        --trusted-host pypi.tuna.tsinghua.edu.cn \
        bitsandbytes==0.42.0 \
        accelerate>=0.30.1 \
        transformers==4.45.2 \
        peft>=0.11.1 \
        transformers_stream_generator \
        torch==2.1.2 \
        torchvision \
        # gradio==4.42.0 \
        gradio==4.38.0 \
        gradio_client==1.3.0


RUN pip install --no-cache-dir  \
        -i https://pypi.tuna.tsinghua.edu.cn/simple  \
        --trusted-host pypi.tuna.tsinghua.edu.cn \
        av==12.3.0 \
        decord==0.6.0 \
        numpy \
        Pillow==10.2.0 \
        uvicorn \
        tiktoken \
        sentencepiece==0.1.99 \
        trl>=0.8.6 \
        packaging==23.2 \
        addict==2.4.0 \
        editdistance==0.6.2 \
        einops==0.7.0 \
        fairscale==0.4.0 \
        jsonlines==4.0.0 \
        markdown2==2.4.10 \
        more_itertools==10.1.0 \
        nltk==3.8.1 \
        # pydantic \
        pydantic==1.10.13 \
        pydantic_core \
        fastapi \
        starlette \
        requests \
        opencv_python_headless==4.5.5.64 \
        openpyxl==3.1.2 \
        sacrebleu==2.3.2 \
        seaborn==0.13.0 \
        shortuuid==1.0.11 \
        protobuf==4.25.0 \
        spacy \
        timm==0.9.10 \
        tqdm==4.66.1 \
        typing_extensions==4.8.0


RUN wget https://cdn-media.hf-mirror.com/frpc-gradio-0.2/frpc_linux_amd64 && \
    mv frpc_linux_amd64 frpc_linux_amd64_v0.2 && \
    mv frpc_linux_amd64_v0.2 /opt/conda/lib/python3.10/site-packages/gradio/ && \
    chmod 755 /opt/conda/lib/python3.10/site-packages/gradio/frpc_linux_amd64_v0.2

WORKDIR /app
COPY examples/qwen2vl_web_gradio.py /app
COPY examples/qwen2vl_vision_process.py /app
RUN chmod u+x /app/qwen2vl_web_gradio.py

RUN openssl req -x509 -days 3650 -nodes -newkey rsa  \
    -keyout ./key.pem -out ./cert.pem -subj "/CN=ChatTTS"

EXPOSE 7860

