# Dockerfile-gpu
FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-devel

RUN apt-get update -y --allow-unauthenticated
RUN apt install -y git vim git-lfs

#设置工作目录
WORKDIR /workspace

COPY examples/llama_chat_gradio.py /workspace
COPY examples/chatglm_chat_gradio.py /workspace
COPY examples/chatglm3_chat_gradio.py /workspace

RUN pip install --no-cache-dir \
    -i https://pypi.tuna.tsinghua.edu.cn/simple \
    --trusted-host pypi.tuna.tsinghua.edu.cn \
    bitsandbytes==0.42.0 \
    accelerate==0.30.1 \
    numpy==1.26.4 \
    gekko==1.0.6 \
    pandas \
    scipy \
    sentencepiece==0.2.0 \
    datasets \
    evaluate \
    pytest \
    peft==0.10.0 \
    transformers==4.42.3 \
    deepspeed==0.14.0 \
    scikit-learn \
    torchvision \
    torchdata \
    torchaudio \
    tensorboard \
    gradio \
    packaging \
    tqdm \
    rouge \
    jieba \
    fuzzywuzzy \
    einops \
    tiktoken \
    xformers \
    streamlit \
    cpm_kernels

RUN pip install --no-cache-dir flash_attn --no-build-isolation

RUN chmod u+x /workspace/llama_chat_gradio.py
RUN chmod u+x /workspace/chatglm_chat_gradio.py
RUN chmod u+x /workspace/chatglm3_chat_gradio.py

#开启7860端口
EXPOSE 7860

#设置启动命令
#ENTRYPOINT ["python", "llama_chat_gradio.py", \
#            "--model_name_or_path=/workspace/models"]
